### ISSUE TITLE
Newer version of owasp/zap2docker-live image HTML report elements are no longer parsing correctly

### ISSUE THREAD

**Issue by mig5** [Accruent/owasp-zap-historic-parser#71]
Hello,

Thanks for your work on the OWASP ZAP Historical tools! I'm making heavy use of them and have even customized them somewhat to support better user management in the web interface (along with role-based permissions for reading vs adding new projects/users etc), reading in database configs from file rather than passing passwords on the CLI, adding some trend graphs etc. I'll be glad to send in some patches at some stage if interested.

I've recently upgraded to the latest owasp/zap2docker-live Docker image which was updated 2 weeks ago from time of writing. (From https://hub.docker.com/r/owasp/zap2docker-live)

It looks like the HTML reports have changed a fair bit in recent releases (I'm not sure when exactly, the last time I pulled the image was 3 months ago), which has broken the ability for the owasp-zap-historic-parser to properly parse the HTML.

For example, the old output might've looked like this (parses perfectly using your tool):

```
       <h3>Alert Detail</h3>
        <div class="spacer"></div>
        <table width="100%" class="results">
              
  
  
  
            <tr height="24" class="risk-high">
                <th width="20%"><a name="high"></a>High (High)</th><th width="80%">PII Disclosure</th>
            </tr>
              
  
  
  
            <tr bgcolor="#e8e8e8">
                <td width="20%">Description</td><td width="80%"><p>The response contains Personally Identifiable Information, such as CC number, SSN and similar sensitive data.</p></td>
            </tr>
            <TR vAlign="top">
                <TD colspan="2"></TD>
            </TR>
              
```

The new output for the same alert, now looks like this:

```
	<h3>Alerts</h3>
		<table class="alerts">
			<tr>
				<th width="60%" height="24">Name</th>
				<th width="20%"
					align="center">Risk Level</th>
				<th width="20%"
					align="center">Number of Instances</th>
			</tr>
			<tr>
				<td><a href="#10062">PII Disclosure</a></td>
				<td align="center" class="risk-3">High</td>
				<td align="center">2</td>
			</tr>
```

The net effect is that there are zero results in the ZAP Historic web interface after having upgraded ZAP.

I've tried to tweak the parser's code, but can't figure out the right syntax to fix the HTML parsing to not only search on the 'class=alerts' table but also deal with the fact that the finding's Title, severity etc are now in separate `<tr>` elements - appreciate if someone could take a look!

Thanks again for this great addition to ZAP testing!

**Comment by neiljhowell** [comment]
Hi @mig5,

Thanks for bringing up this issue! I had very recently seen what looked like a newer version of the ZAP report and immediately thought that those changes would probably break the parser. It must be that in the bulk of our current ZAP testing we are still using some older version of the ZAP testing tool.

I remember that initially I could choose between json, xml, and html outputs - and I eventually chose to parse the html report because I knew that I wanted the user to be able to view the report anyway and was pretty comfortable coming up with xpaths for GUI testing. With this new report it may be time to revisit potentially parsing the json or xml output if they are still available as outputs. It may even be possible to reconfigure the parser to be able to parse and store different versions of the report.

I haven't had much time to work on this since standing it up, but it's quite possible that with some current CICD work we are doing at Accruent we will need to be able to parse and store from this newer version of the report. I can see this happening by the end of the year. In the meantime, I will try and find a copy of the newer report and work on updating the parser in my free time.

I'd love to see any updates/patches that you've made. Currently with the application, I am mainly focusing on completing the unit testing so that we can completely leverage dependabot and stay current with libraries. Again, having time to work on it is the biggest blocker right now. The application was always meant to have graphs at some point that would add context, so I'd love to see what you've added and how your users are consuming it.

Hopefully I'll get some time to work on this soon.

**Comment by mig5** [comment]
Thanks very much @neiljhowell ! Indeed I wondered if parsing the json or xml reports would be a bit more reliable, but I think there's every chance that an upstream change could affect even those formats.. probably inevitable.

One of my more shameful hacks to your app was actually also sending the full HTML report as an embedded blob into the database so that the report was visible directly in the web interface :D Not proud of that one - but a reason why I'd be happy if it still worked against the HTML report at least as an option.

Thanks again, I hope to 'soon' (like yourself: finding time outside of day-to-day work is always the hard part) send some PoC pull requests with some of my changes at least for interest's sake (you don't have to accept them). My own copy of your repos has fallen behind on some of your dependabot updates so I myself have some updating to do.. and we'll see if I have to rework my changes as a result. 

Speak soon!

**Comment by neiljhowell** [comment]
@mig5 I started tinkering with this last Friday and am making some progress. Do you happen to have a report that has false positives on it that I can use to test with?

**Comment by mig5** [comment]
Hi @neiljhowell - attached is a report that was generated with a newer ZAP docker image and contains the new table format/styles. It has a mix of false positives (totally incorrect detection of PII) as well as valid findings, I've sanitized URLs a bit is all. Hope it helps!

Note, I've added a `.txt` file extension suffix just to allow it to upload in Github, you'll want to rename it.

[report.html.txt](https://github.com/Accruent/owasp-zap-historic-parser/files/6942179/report.html.txt)

**Comment by neiljhowell** [comment]
Thanks, but I was hoping for a report that actually found False Positives and shows what the report does with them - I am assuming that the report handles False Positive alerts the same way that it handles other alerts, but I have not yet seen a report that shows any False Positives on it. Unfortunately that leaves the unit testing coverage at 99%. I might go ahead and push this change and deal with fixing the code if it turns out the report handles them differently.

**Comment by mig5** [comment]
Sorry @neiljhowell - I don't think I've ever seen a false positive explicitly stated as such in a ZAP report. For me, false positives have always been a human-detected thing. Maybe I'm doing it wrong :) Thanks for working on it!

**Comment by neiljhowell** [comment]
@mig5 can you try this release when you get a chance? FYI there are also DB changes that need to be made, adding a False Positives field in TB_PROJECT as well as any projects TB_EXECUTION tables. DB scripts are in the release notes.

**Comment by mig5** [comment]
@neiljhowell sorry it's taken me so long to be able to test this. I can confirm everything is working great with your changes when using the latest zap2docker-weekly Docker image.

Many thanks for all your excellent work on this, I really appreciate it!
